services:
  app:
    build: .
    command: hypercorn --bind 0.0.0.0:55000 --reload taskmates.server.server:app
    ports:
      - 55000:55000
    volumes:
      - .:/app
  shell:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
