[runner_config]
format = "completion"
interactive = true

# Completion Context
[runner_environment]
markdown_path = "{uuid4()}.md"
cwd = "{os.getcwd()}"

# Completion Options
[run_opts]
model = "claude-3-5-sonnet-20241022"
max_steps = 10000

[[run_opts.taskmates_dirs]]
path = "{os.environ.get('TASKMATES_HOME', str(Path.home() / '.taskmates'))}"

[[run_opts.taskmates_dirs]]
path = "{root_path() / 'taskmates' / 'default_config'}"


[profile.api]



[profile.cli]
